#!/usr/bin/env node
'use strict';

// 把 Spine 素材(骨架 json / atlas / 贴图 png)打包成 data URI,生成
// renderer/spine-data.js 供 spine-player 的 rawDataURIs 使用。
// 这样渲染页无论走 file:// 还是 http:// 都不需要跨域读文件。

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SPINE_DIR = path.join(ROOT, 'assets', 'spine');
const OUT = path.join(ROOT, 'renderer', 'spine-data.js');

// 素材文件名可用环境变量覆盖:REMI_SKEL / REMI_ATLAS / REMI_PNG
const SKEL = process.env.REMI_SKEL || 'remi.json';
const ATLAS = process.env.REMI_ATLAS || 'leimi.atlas';
const PNG = process.env.REMI_PNG || 'leimi.png';

function dataUri(file, mime) {
  const full = path.join(SPINE_DIR, file);
  if (!fs.existsSync(full)) {
    console.error(`\n❌ 找不到素材:${full}\n`);
    console.error('本仓库不含美术素材(角色 IP 与素材作者的权利都不属于本项目),需要你自备:');
    console.error('  1. 准备一套 Spine 4.2 导出的素材(骨架 .json + .atlas + 贴图 .png)');
    console.error(`  2. 放进 ${SPINE_DIR}/`);
    console.error(`  3. 文件名默认为 ${SKEL} / ${ATLAS} / ${PNG},`);
    console.error('     不一致可用 REMI_SKEL=xx.json REMI_ATLAS=xx.atlas REMI_PNG=xx.png 覆盖');
    console.error('  4. 动画名需与 shared/states.js 的 STATE_ANIM 对应,');
    console.error('     可用 npx electron scripts/frames-main.js 逐动画拆帧确认\n');
    process.exit(1);
  }
  return `data:${mime};base64,${fs.readFileSync(full).toString('base64')}`;
}

const payload = {
  skeleton: SKEL,
  atlas: ATLAS,
  rawDataURIs: {
    [SKEL]: dataUri(SKEL, 'application/json'),
    [ATLAS]: dataUri(ATLAS, 'text/plain'),
    [PNG]: dataUri(PNG, 'image/png'),
  },
};

fs.writeFileSync(OUT, `// generated by scripts/gen-assets.js — do not edit\nwindow.REMI_SPINE = ${JSON.stringify(payload)};\n`);
console.log('wrote', OUT, fs.statSync(OUT).size, 'bytes');
